config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'users#show'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                format: { with: URI::MailTo::EMAIL_REGEXP },
                uniqueness: {case_sensitive: false}
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_path
    else
      falsh.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to login_url
  end

  private
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user_id
      return true
    else
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: session[:user_id])
    if !@user
      return redirect_to login_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id # ユーザー登録後、そのままログイン状態にするため、セッションにユーザーIDを保存
      flash[:success] = '登録しました' # flashハッシュにsuccessというキーでメッセージ'登録しました'を、次のリクエスト（通常はリダイレクト後のページ）までメッセージを保持し、表示する
      redirect_to root_path # rootパスにリダイレクト
    else
      flash.now[:danger] = '登録できませんでした' # flash.nowハッシュにdangerというキーでメッセージ'登録できませんでした'を、次のリクエストまでではなく、そのリクエスト内でのみメッセージを保持し、表示する
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(
      :name, :email, :password, :password_confirmation
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/commons/_flash.html.erb
<% flash.each do |type, message| %>
    <div class="alert alert-<%= type %>"><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hinoki</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Railsのユーザー認証</h1>
    <p>
      <%= link_to '会員登録', signup_path %>
      <%= link_to 'ログイン', login_path %>
      <%= link_to 'HOME', root_path%>
      <%= link_to 'ログアウト', logout_path, method: :delete%>
    </p>
    <%= render 'commons/flash'%>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h3>会員登録</h3>
<%= form_with(model: @user, url: signup_path) do |f| %>
<dl>
    <dt>名前</dt>
    <dd><%= f.text_field :name %></dd> 
    <dt>E-mail</dt> 
    <dd><%= f.email_field :email %></dd>
    <dt>パスワード</dt>
    <dd><%= f.password_field :password %></dd>
    <dt>パスワード（確認用）</dt>
    <dd><%= f.password_field :password_confirmation %></dd>
</dl>
<%= f.submit '会員登録' %>
<% end %>

app/views/users/show.html.erb
<h3><%= @user.name %>さん、ようこそ</h3>